routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Route::get('mddc-login', 'LoginController@index');
Route::get('login', 'LoginController@index')->name('login');
Route::post('authlogin', 'LoginController@authentication');
Route::get('logout', 'LoginController@logout');

// Frontend
Route::get('/', 'User\HomeController@index');
Route::get('read/{id}/{slug}', 'User\ArticlesController@read');
Route::get('programming', 'User\ProgrammingController@index');
Route::get('traveling', 'User\TravelingController@index');
Route::get('tips', 'User\TipsController@index');
Route::get('masakan', 'User\MasakanController@index');
Route::get('opini', 'User\OpiniController@index');
Route::get('ebook', 'User\EbookController@index');

Route::get('cari', 'User\CariController@index');
Route::post('cari-artikel', 'User\CariController@cari');

Route::middleware('auth')->group(function () {

	// Admin
	Route::get('admin', 'Admin\HomeController@index');
	Route::resource('users', 'Admin\UserController');
	Route::resource('categories', 'Admin\CategoriesController');
	Route::resource('articles', 'Admin\ArticlesController');
	Route::resource('ebooks', 'Admin\EbookController');
	Route::resource('youtube', 'Admin\YoutubeController');
});

app/Models/Youtube.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Youtube extends Model
{
    protected $table = 'youtube';
    protected $primaryKey = 'id';
    protected $guarded = [];
}

app/Http/Controllers/Admin/YoutubeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Youtube;

use Illuminate\Support\Facades\Auth;
use App\Libraries\Utils\DateFormat;

class YoutubeController extends Controller
{
    public function index(){
    	$data['list'] = Youtube::all();
    	return view('admin.youtube.list', $data);
    }

    public function create(){
    	return view('admin.youtube.create');
    }

    public function store(Request $request){
        // Upload Data
        $dokFiles = [
            'cover'
        ]; 
        
        $data = [];

        foreach ($dokFiles as $file) {
            if($request->file($file) != ''){
                $data[$file] = $this->uploadFileDok($request->title, $file, $request->file($file));
            }
        }

        $data['title'] = $request->title;
        $data['youtube_link'] = $request->youtube_link;
        $data['status_publish'] = $request->status_publish;
        $data['date_publish'] =  DateFormat::convertToDateDb($request->date_publish);
        $data['author'] = Auth::user()->name;
        $data['slug'] =  strtolower(str_replace(" ","-", $request->title));

    	$simpan = Youtube::create($data);

    	if ($simpan){
    		return redirect()->route('youtube.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('youtube.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function edit($id){
    	$data['row'] = Youtube::findOrFail($id);

      	return view('admin.youtube.edit', $data);
    }

    public function update(Request $request, $id){
    	$table = Youtube::findOrFail($id);

    	// Upload Data
        $dokFiles = [
            'cover'
        ]; 
        
        $data = [];

        foreach ($dokFiles as $file) {
            if($request->file($file) != ''){
                $data[$file] = $this->uploadFileDok($request->title, $file, $request->file($file));
            }
        }

        $data['title'] = $request->title;
        $data['youtube_link'] = $request->youtube_link;
        $data['status_publish'] = $request->status_publish;
        $data['date_publish'] =  DateFormat::convertToDateDb($request->date_publish);
        $data['author'] = Auth::user()->name;
        $data['slug'] =  strtolower(str_replace(" ","-", $request->title));

    	$ubah = $table->fill($data)->save();

    	if ($ubah){
    		return redirect()->route('youtube.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('youtube.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function destroy($id){
        $response = ['status' => 'error', 'message' => 'Data gagal terhapus.'];

        $table = Youtube::findOrFail($id);
        if ($table->delete()) {
            $response['status'] = 'success';
        }

        return response()->json($response);
    }
    
    
    public function uploadFileDok($title, $file_name, $file)
    {

        $fileExtention  = $file->getClientOriginalExtension();
        $fileName       = $file_name.'_'.strtolower(str_replace(" ","_",$title)).'.'.$fileExtention;

        $file->move(public_path('uploads/youtube/'), $fileName);

        return $fileName;
    }

}

resources/views/admin/youtube/create.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'youtube'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Tambah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('youtube') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('youtube.store') }}" method="POST" enctype="multipart/form-data">
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-8">
		                                <div class="form-group form-show-validation row">
		                                    <div class="col-md-12">
		                                        <input type="text" class="form-control" name="title" placeholder="Enter Title" required>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <div class="col-md-12">
		                                        <input type="text" class="form-control" name="youtube_link" placeholder="Link Youtube" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="col-md-4">
		                            	<div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Status
		                            		</label>
		                            		<div class="col-md-8">
			                            		<select class="form-control select2" name="status_publish">
			                            			<option value="1">Published</option>
			                            			<option value="2">Un Published</option>
			                            		</select>
			                            	</div>
		                                </div>

		                                <div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Publish On
		                            		</label>
		                            		<div class="col-md-8">
		                            			<input type="text" class="form-control datepicker" name="date_publish" placeholder="Date Publish" required>
		                            		</div>
		                                </div>

		                                <div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Cover
		                            		</label>
		                            		<div class="col-md-8">
			                            		<input type="file" class="form-control" name="cover">
			                            	</div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')

@endsection

resources/views/admin/youtube/edit.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'youtube'])

@php($DateFormat = 'App\Libraries\Utils\DateFormat')

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Ubah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('youtube') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('youtube.update', $row->id) }}" method="POST" enctype="multipart/form-data">
							{{ method_field('PATCH') }}
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-8">
		                                <div class="form-group form-show-validation row">
		                                    <div class="col-md-12">
		                                        <input type="text" class="form-control" name="title" placeholder="Enter Title" value="{{ $row->title }}" required>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <div class="col-md-12">
		                                        <input type="text" class="form-control" name="youtube_link" placeholder="Link Youtube" value="{{ $row->youtube_link }}" required>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="col-md-4">
		                            	<div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Status
		                            		</label>
		                            		<div class="col-md-8">
			                            		<select class="form-control select2" name="status_publish">
			                            			<option value="1" {{ ($row->status_publish == 1) ? "selected" : "" }}>Published</option>
			                            			<option value="2" {{ ($row->status_publish == 2) ? "selected" : "" }}>Un Published</option>
			                            		</select>
			                            	</div>
		                                </div>

		                                <div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Publish On
		                            		</label>
		                            		<div class="col-md-8">
		                            			<input type="text" class="form-control datepicker" name="date_publish" placeholder="Date Publish" value="{{ $DateFormat::convertToDate($row->date_publish) }}" required>
		                            		</div>
		                                </div>

		                                <div class="form-group form-show-validation row">
		                            		<label class="col-md-4 mt-sm-2 text-right">
		                            			Cover
		                            		</label>
		                            		<div class="col-md-8">
			                            		<input type="file" class="form-control" name="cover">
			                            	</div>

			                            	<div class="col-md-12">
												<img src="{{ asset('uploads/youtube/'.$row->cover) }}" class="img-thumb-prev">
											</div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')

@endsection

resources/views/admin/youtube/list.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'youtube'])

@php($Publish = 'App\Constant\StatusPublish')
@php($DateFormat = 'App\Libraries\Utils\DateFormat')

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">List Youtube</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('youtube/create') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-plus mr-2"></i> Tambah Data
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<div class="table-responsive">
							<table class="display table table-head-bg-primary table-striped table-hover datatables">
								<thead>
									<tr>
										<th class="no">No.</th>
										<th>Thumb</th>
										<th>Title</th>
										<th>Date</th>
										<th class="action">Action</th>
									</tr>
								</thead>
								<tbody>
									@foreach($list as $key => $val)
									<tr>
										<td class="no">{{ $key+1 }}.</td>
										<td>
											<img class="img-thumb" src="{{ asset('uploads/youtube/'. $val->cover) }}">
										</td>
										<td>{{ $val->title }}</td>
										<td>{{ $DateFormat::convertToDate($val->date_publish) }}</td>
										<td class="action">
											<div class="btn-group" role="group" aria-label="Basic example">
	                                            <a href="{{ url('youtube/'. $val->id .'/edit') }}"
	                                               class="btn btn-primary btn-sm" data-toggle="tooltip"
	                                               title="Ubah Data"><i class="fas fa-edit"></i>
	                                            </a>
	                                            <button class="btn btn-danger btn-sm hapus" data-toggle="tooltip"
	                                                title="Hapus Data" data-id="{{ $val->id }}">
	                                                <i class="fas fa-trash-alt"></i>
	                                            </button>
	                                        </div>
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- For Delete Data Url -->
<input type="hidden" id="baseUrl" value="{{ url('youtube') }}">
<input type="hidden" id="token" value="{{ csrf_token() }}">
@endsection

@section('javascript')

@endsection