routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Route::get('mddc-login', 'LoginController@index');
Route::get('login', 'LoginController@index')->name('login');
Route::post('authlogin', 'LoginController@authentication');
Route::get('logout', 'LoginController@logout');

// Frontend
Route::get('/', 'User\HomeController@index');
Route::get('read/{id}/{slug}', 'User\ArticlesController@read');
Route::get('programming', 'User\ProgrammingController@index');
Route::get('traveling', 'User\TravelingController@index');
Route::get('tips', 'User\TipsController@index');
Route::get('masakan', 'User\MasakanController@index');
Route::get('opini', 'User\OpiniController@index');
Route::get('ebook', 'User\EbookController@index');

Route::get('cari', 'User\CariController@index');
Route::post('cari-artikel', 'User\CariController@cari');

Route::middleware('auth')->group(function () {

	// Admin
	Route::get('admin', 'Admin\HomeController@index');
	Route::resource('users', 'Admin\UserController');
	Route::resource('categories', 'Admin\CategoriesController');
	Route::resource('articles', 'Admin\ArticlesController');
	Route::resource('ebooks', 'Admin\EbookController');
	Route::resource('youtube', 'Admin\YoutubeController');
});

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Categories;

class CategoriesController extends Controller
{
    public function index(){
    	$data['list'] = Categories::all();
    	return view('admin.categories.list', $data);
    }

    public function create(){
    	return view('admin.categories.create');
    }

    public function store(Request $request){
    	$data = [
    		'category' 		=> $request->category
    	];

    	$simpan = Categories::create($data);

    	if ($simpan){
    		return redirect()->route('categories.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('categories.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function edit($id){
    	$data['row'] = Categories::findOrFail($id);
      	return view('admin.categories.edit', $data);
    }

    public function update(Request $request, $id){
    	$table = Categories::findOrFail($id);

    	$data = [
            'category'      => $request->category
        ];

    	$ubah = $table->fill($data)->save();

    	if ($ubah){
    		return redirect()->route('categories.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('categories.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function destroy($id){
        $response = ['status' => 'error', 'message' => 'Data gagal terhapus.'];

        $table = Categories::findOrFail($id);
        if ($table->delete()) {
            $response['status'] = 'success';
        }

        return response()->json($response);
    }

}

resources/views/admin/categories/create.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'categories'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Tambah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('categories') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('categories.store') }}" method="POST">
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Category <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="text" class="form-control" name="category" placeholder="Category" required>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'categories'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Ubah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('categories') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('categories.update', $row->id) }}" method="POST">
							{{ method_field('PATCH') }}
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Category <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="text" class="form-control" name="category" placeholder="Category" value="{{ $row->category }}" required>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'categories'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">List Category</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('categories/create') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-plus mr-2"></i> Tambah Data
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<div class="table-responsive">
							<table class="display table table-head-bg-primary table-striped table-hover datatables">
								<thead>
									<tr>
										<th class="no">No.</th>
										<th>Category</th>
										<th class="action">Action</th>
									</tr>
								</thead>
								<tbody>
									@foreach($list as $key => $val)
									<tr>
										<td class="no">{{ $key+1 }}.</td>
										<td>{{ $val->category }}</td>
										<td class="action">
											<div class="btn-group" role="group" aria-label="Basic example">
	                                            <a href="{{ url('categories/'. $val->id .'/edit') }}"
	                                               class="btn btn-primary btn-sm" data-toggle="tooltip"
	                                               title="Ubah Data"><i class="fas fa-edit"></i>
	                                            </a>
	                                            <button class="btn btn-danger btn-sm hapus" data-toggle="tooltip"
	                                                title="Hapus Data" data-id="{{ $val->id }}">
	                                                <i class="fas fa-trash-alt"></i>
	                                            </button>
	                                        </div>
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- For Delete Data Url -->
<input type="hidden" id="baseUrl" value="{{ url('categories') }}">
<input type="hidden" id="token" value="{{ csrf_token() }}">
@endsection

@section('javascript')

@endsection