routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth
Route::get('mddc-login', 'LoginController@index');
Route::get('login', 'LoginController@index')->name('login');
Route::post('authlogin', 'LoginController@authentication');
Route::get('logout', 'LoginController@logout');

// Frontend
Route::get('/', 'User\HomeController@index');
Route::get('read/{id}/{slug}', 'User\ArticlesController@read');
Route::get('programming', 'User\ProgrammingController@index');
Route::get('traveling', 'User\TravelingController@index');
Route::get('tips', 'User\TipsController@index');
Route::get('masakan', 'User\MasakanController@index');
Route::get('opini', 'User\OpiniController@index');
Route::get('ebook', 'User\EbookController@index');

Route::get('cari', 'User\CariController@index');
Route::post('cari-artikel', 'User\CariController@cari');

Route::middleware('auth')->group(function () {

	// Admin
	Route::get('admin', 'Admin\HomeController@index');
	Route::resource('users', 'Admin\UserController');
	Route::resource('categories', 'Admin\CategoriesController');
	Route::resource('articles', 'Admin\ArticlesController');
	Route::resource('ebooks', 'Admin\EbookController');
	Route::resource('youtube', 'Admin\YoutubeController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';
    protected $primaryKey = 'id';
    protected $guarded = [];

    protected $fillable = [
        'name', 'email', 'password', 'hak_akses'
    ];

    protected $hidden = [
        'password', 'remember_token', 'name'
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\User;
use App\Constants\HakAkses;

class UserController extends Controller
{
    public function index(){
    	$data['list'] = User::all();
    	return view('admin.user.list', $data);
    }

    public function create(){
    	return view('admin.user.create');
    }

    public function store(Request $request){
    	$MailExist = User::where('email', $request->email)->count();

    	if($MailExist){
    		return redirect()->route('users.index')->with('alert-error', 'Email Sudah Pernah Ada, Silahkan Masukkan Email Lain');
    	}

    	$data = [
    		'name' 			=> $request->name,
    		'email' 		=> $request->email,
    		'password' 		=> bcrypt($request->cpassword),
    		'hak_akses'		=> $request->hak_akses,
    	];

    	$simpan = User::create($data);

    	if ($simpan){
    		return redirect()->route('users.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('users.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function edit($id){
    	$data['row'] = User::findOrFail($id);
      	return view('admin.user.edit', $data);
    }

    public function update(Request $request, $id){
    	$table = User::findOrFail($id);

    	$data['name'] 	= $request->name;

    	if($request->cpassword != ""){
    		$data['password'] 	= bcrypt($request->cpassword);
    	}

    	$data['hak_akses'] 	= $request->hak_akses;

    	$ubah = $table->fill($data)->save();

    	if ($ubah){
    		return redirect()->route('users.index')->with('alert-success', 'Data Berhasil Disimpan.');
    	}else{
    		return redirect()->route('users.index')->with('alert-error', 'Data Gagal Disimpan.');
    	}
    }

    public function destroy($id){
        $response = ['status' => 'error', 'message' => 'Data gagal terhapus.'];

        $table = User::findOrFail($id);
        if ($table->delete()) {
            $response['status'] = 'success';
        }

        return response()->json($response);
    }
}

app/Http/Controllers/User/ArticlesController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class ArticlesController extends Controller
{
    public function __construct()
    {

    }

    public function read(Request $request, $id, $slug){
        $data['rowArtikel'] = Articles::where('id', $id)->first();

        $slugDb = $data['rowArtikel']->slug;

        if($slug == $slugDb){
                $data['prevArtikel'] = Articles::where('status_publish', 1)
            ->where('date_publish','>',$data['rowArtikel']->date_publish)
            ->orderby('date_publish','ASC')->limit(0,1)->first();

            $data['nextArtikel'] = Articles::where('status_publish', 1)
                ->where('date_publish','<',$data['rowArtikel']->date_publish)
                ->orderby('date_publish','DESC')->limit(0,1)->first();

            // Update View Article
            $table = Articles::findOrFail($id);

            $totalView = $table->view;

            $dataArticle['view'] = $totalView + 1;

            $ubah = $table->fill($dataArticle)->save();

            return view('user.read', $data);
        }else{
            return redirect('read/'.$id.'/'.$slugDb);
        }
    }
}

app/Http/Controllers/User/CariController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class CariController extends Controller
{
    public function __construct()
    {

    }

    public function index(){
    	return view('user.pencarian');
    }

    private $paginate = 10;
    public function cari(Request $request){
        $data['keyword'] = $request->cari;

        $data['number'] = 1;

        $list = Articles::where('title', 'like', '%'.$data['keyword'].'%')->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

        return view('user.hasil_pencarian', $data);
    }
}

app/Http/Controllers/User/EbookController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Ebook;


class EbookController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Ebook";

        $data['number'] = 1;

        $list = Ebook::where('status_publish', 1)->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal_ebook', $data);
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;
use App\Models\Ebook;

class HomeController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        // $data['listArtikel'] = Articles::where('status_publish', 1)->orderBy('date_publish', 'DESC')->get();

        $data['number'] = 1;

        $listArtikel = Articles::where('status_publish', 1)->orderBy('date_publish', 'DESC');

        $data['total']  = $listArtikel->count();
        $data['listArtikel']   = $listArtikel->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

        $data['ebookUpdate'] = Ebook::where('status_publish', 1)->orderBy('date_publish', 'DESC')->limit(1)->first();

    	return view('user.home', $data);
    }
}

app/Http/Controllers/User/MasakanController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class MasakanController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Masakan";

        $data['number'] = 1;

        $list = Articles::where('status_publish', 1)->where('id_categories','7')
            ->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal', $data);
    }
}

app/Http/Controllers/User/OpiniController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class OpiniController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Opini";

        $data['number'] = 1;

        $list = Articles::where('status_publish', 1)->where('id_categories','5')
            ->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal', $data);
    }
}

app/Http/Controllers/User/ProgrammingController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class ProgrammingController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Programming";

        $data['number'] = 1;

        $list = Articles::where('status_publish', 1)->where('id_categories','2')
            ->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal', $data);
    }
}

app/Http/Controllers/User/TipsController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class TipsController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Tips";

        $data['number'] = 1;

        $list = Articles::where('status_publish', 1)->where('id_categories','4')
            ->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal', $data);
    }
}

app/Http/Controllers/User/TravelingController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Articles;


class TravelingController extends Controller
{
    public function __construct()
    {

    }

    private $paginate = 9;

    public function index(Request $request){
        $data['kategori'] = "Traveling";

        $data['number'] = 1;

        $list = Articles::where('status_publish', 1)->where('id_categories','3')
            ->orderBy('date_publish', 'DESC');

        $data['total']  = $list->count();
        $data['list']   = $list->paginate($this->paginate);

        if ($request->page) {
            $data['number'] = ($request->page * $this->paginate) - $this->paginate + 1;
        }

    	return view('user.sub_kanal', $data);
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'users'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Tambah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('users') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('users.store') }}" method="POST">
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Email <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="email" class="form-control" name="email" placeholder="Email" required>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Nama User <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="text" class="form-control" name="name" placeholder="Nama User" required>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Password <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                    	<div class="form-icon">
			                                        <input type="password" class="form-control" id="password" name="password" placeholder="Password" onchange="" required>
			                                        <span toggle="#password-field" class="fas fa-eye field-icon toggle-password"></span>
		                                    	</div>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Ulangi Password <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                    	<div class="form-icon">
			                                        <input type="password" class="form-control" id="cpassword" name="cpassword" placeholder="Ulangi Password" required>
			                                        <span toggle="#password-field" class="fas fa-eye field-icon toggle-cpassword"></span>
		                                    	</div>
		                                        <div class="text-danger mt-2" id="msg-cpassword"></div>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Hak Akses <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <select class="form-control select2" name="hak_akses" required>
		                                        	<option value="" selected disabled>Pilih Data</option>
		                                        	<option value="1">Admin</option>
		                                        	<option value="2">Staff</option>
		                                        </select>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
	<script>
		$('#cpassword').keyup(function (){
	  		// Validate
			var msg = document.getElementById('msg-cpassword');
			var val_password = $('#password').val();
			var val_cpassword = $('#cpassword').val();
			
			if(val_password != val_cpassword)
		    {
		        msg.style.display = "block";
		        msg.innerHTML = "Password tidak sama";
		    }else{
		    	msg.style.display = "none";
		    }
	  	});

	  	$('#password').keyup(function (){
	  		// Validate
			var msg = document.getElementById('msg-cpassword');
			var val_password = $('#password').val();
			var val_cpassword = $('#cpassword').val();
			
			if (val_cpassword != ""){
				if(val_password != val_cpassword)
			    {
			        msg.style.display = "block";
			        msg.innerHTML = "Password tidak sama";
			    }else{
			    	msg.style.display = "none";
			    }
			}
	  	});

	  	$(".toggle-password").click(function() {
			$(this).toggleClass("fa-eye fa-eye-slash");

			var password = document.getElementById('password');
			if (password.type === "password") {
				password.type = "text";
				$('#password_show').text("Hide");
			} else {
				password.type = "password";
				$('#password_show').text("Show");
			}
		});

		$(".toggle-cpassword").click(function() {
			$(this).toggleClass("fa-eye fa-eye-slash");

			var password = document.getElementById('cpassword');
			if (password.type === "password") {
				password.type = "text";
				$('#password_show').text("Hide");
			} else {
				password.type = "password";
				$('#password_show').text("Show");
			}
		});
	</script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'users'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">Ubah Data</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('users') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-arrow-left mr-2"></i> Kembali ke List
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<form action="{{ route('users.update', $row->id) }}" method="POST">
							{{ method_field('PATCH') }}
		                    {{ csrf_field() }}
		                    <div class="card-body">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Email <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="email" class="form-control" name="email" placeholder="Email" 
		                                        	value="{{ $row->email }}" readonly>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Nama User <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <input type="text" class="form-control" name="name" placeholder="Nama User" 
		                                        	value="{{ $row->name }}" required>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
			                                <div class="col-md-2">
			                                	&nbsp;
			                                </div>
			                                <div class="col-md-4">
			                                	<span class="required-label">* Kosongkan password jika tidak mau dirubah</span>
			                                </div>
		                            	</div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Password <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                    	<div class="form-icon">
			                                        <input type="password" class="form-control form-with-icon" id="password" name="password" placeholder="Password">
			                                        <span toggle="#password-field" class="fas fa-eye field-icon toggle-password"></span>
		                                   		</div>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Ulangi Password <span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <div class="form-icon">
			                                        <input type="password" class="form-control" id="cpassword" name="cpassword" placeholder="Ulangi Password" required>
			                                        <span toggle="#password-field" class="fas fa-eye field-icon toggle-cpassword"></span>
		                                    	</div>
		                                        <div class="text-danger mt-2" id="msg-cpassword"></div>
		                                    </div>
		                                </div>
		                                <div class="form-group form-show-validation row">
		                                    <label class="col-md-2 mt-sm-2 text-right">
		                                        Hak Akses<span class="required-label">*</span>
		                                    </label>
		                                    <div class="col-md-4">
		                                        <select class="form-control select2" name="hak_akses" required>
		                                        	<option value="" disabled>Pilih Data</option>
		                                        	<option value="1" {{ ($row->hak_akses == \App\Constant\HakAkses::ADMIN) ? 'selected' : '' }}>Admin</option>
		                                        	<option value="2" {{ ($row->hak_akses == \App\Constant\HakAkses::STAFF) ? 'selected' : '' }}>Staff</option>
		                                        </select>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                    </div>
		                    <div class="card-action">
		                        <div class="row">
		                            <div class="col-md-12">
		                                <button class="btn btn-primary btn-round float-right" type="submit">
		                                	Simpan Data
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('javascript')
	<script>
		$('#cpassword').keyup(function (){
	  		// Validate
			var msg = document.getElementById('msg-cpassword');
			var val_password = $('#password').val();
			var val_cpassword = $('#cpassword').val();
			
			if(val_password != val_cpassword)
		    {
		        msg.style.display = "block";
		        msg.innerHTML = "Password tidak sama";
		    }else{
		    	msg.style.display = "none";
		    }
	  	});

	  	$('#password').keyup(function (){
	  		// Validate
			var msg = document.getElementById('msg-cpassword');
			var val_password = $('#password').val();
			var val_cpassword = $('#cpassword').val();
			
			if (val_cpassword != ""){
				if(val_password != val_cpassword)
			    {
			        msg.style.display = "block";
			        msg.innerHTML = "Password tidak sama";
			    }else{
			    	msg.style.display = "none";
			    }
			}
	  	});

	  	$(".toggle-password").click(function() {
			$(this).toggleClass("fa-eye fa-eye-slash");

			var password = document.getElementById('password');
			if (password.type === "password") {
				password.type = "text";
				$('#password_show').text("Hide");
			} else {
				password.type = "password";
				$('#password_show').text("Show");
			}
		});

		$(".toggle-cpassword").click(function() {
			$(this).toggleClass("fa-eye fa-eye-slash");

			var password = document.getElementById('cpassword');
			if (password.type === "password") {
				password.type = "text";
				$('#password_show').text("Hide");
			} else {
				password.type = "password";
				$('#password_show').text("Show");
			}
		});
	</script>
@endsection

resources/views/admin/user/list.blade.php
@extends('layouts.adm_theme', ['activeMenu' => 'users'])

@section('content')
<div class="content">
	<div class="panel-header bg-primary-gradient">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold">List User</h2>
				</div>
				<div class="ml-md-auto py-2 py-md-0">
					<a href="{{ url('users/create') }}" class="btn btn-white btn-border btn-round mr-2">
						<i class="fas fa-plus mr-2"></i> Tambah Data
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row mt--2">
			<div class="col-md-12">
				<div class="card full-height">
					<div class="card-body">
						<div class="table-responsive">
							<table class="display table table-head-bg-primary table-striped table-hover datatables">
								<thead>
									<tr>
										<th class="no">No.</th>
										<th>Nama</th>
										<th>Email</th>
										<th>Role</th>
										<th class="action">Action</th>
									</tr>
								</thead>
								<tbody>
									@foreach($list as $key => $val)
									<tr>
										<td class="no">{{ $key+1 }}.</td>
										<td>{{ $val->name }}</td>
										<td>{{ $val->email }}</td>
										<td>{{ \App\Constant\HakAkses::getDescription($val->hak_akses) }}</td>
										<td class="action">
											<div class="btn-group" role="group" aria-label="Basic example">
	                                            <a href="{{ url('users/'. $val->id .'/edit') }}"
	                                               class="btn btn-primary btn-sm" data-toggle="tooltip"
	                                               title="Ubah Data"><i class="fas fa-edit"></i>
	                                            </a>
	                                            <button class="btn btn-danger btn-sm hapus" data-toggle="tooltip"
	                                                title="Hapus Data" data-id="{{ $val->id }}">
	                                                <i class="fas fa-trash-alt"></i>
	                                            </button>
	                                        </div>
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- For Delete Data Url -->
<input type="hidden" id="baseUrl" value="{{ url('users') }}">
<input type="hidden" id="token" value="{{ csrf_token() }}">
@endsection

@section('javascript')

@endsection